# Generated by Django 2.2 on 2021-11-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='in_or_out',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
